[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "https://269fdc63-af3d-4eca-8101-8bddc22d6f14:b694b5b1-f97e-49e4-959e-f3c202e3ab91@pypi.tools.uksouth.bink.sh/simple"
verify_ssl = true
name = "pypi-cloud"

[packages]
fastapi = "*"
uvicorn = {extras = ["standard"], version = "*"}
pydantic = "*"
sqlalchemy = {extras = ["asyncio"], version = ">=1.4.33"}  # Workaround https://github.com/sqlalchemy/sqlalchemy/issues/7714
alembic = "*"
asyncpg = "*"
psycopg2-binary = "*"
prettyprinter = "*"
ujson = "*"
sentry-sdk = ">=1.9.6" # adds fastapi integration
prometheus-client = "==0.12.0" # make sure carina.core.cli monkeypatch is still needed and functioning
blinker = "*"
gunicorn = "*"
requests = "*"
rq = "*"
redis = "*"
hiredis = "*"
tenacity = "*"
azure-identity = "*"
azure-keyvault = "*"
azure-storage-blob = "==12.8.1"  # version 12.9.0 & 12.10.0 have bad type annotations
apscheduler = "*"
retry-tasks-lib = {version=">=1.15.0", index="pypi-cloud"}
fastapi-prometheus-metrics = {version=">=0.2.2", index="pypi-cloud"}
pyyaml = "*"
typer = "*"
cryptography = "*"
cosmos-message-lib = {version=">=1.2.0", index="pypi-cloud"}

[dev-packages]
isort = "*"
black = "*"
mypy = "*"
ipython = "*"
pytest = "*"
pytest-cov = "*"
xenon = "*"
httpretty = "*"
pytest-asyncio = "*"
sqlalchemy-utils = "*"
pytest-mock = "*"
types-redis = "*"
types-requests = "*"
types-pyyaml = "*"
pylint = "*"
pylint-pytest = "*"
testfixtures = "*"

[requires]
python_version = "3.10"
